CREATE TABLE `servers` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(100) NOT NULL COMMENT '服务器名称',
    `host` VARCHAR(255) NOT NULL COMMENT '服务器地址',
    `description` VARCHAR(500) DEFAULT NULL COMMENT '服务器备注说明',
    `status` VARCHAR(20) NOT NULL DEFAULT 'offline' COMMENT '服务器状态: online/offline/unknown',
    `ssh_host` VARCHAR(255) NOT NULL COMMENT 'SSH 地址',
    `ssh_port` INT UNSIGNED NOT NULL DEFAULT 22 COMMENT 'SSH 端口',
    `ssh_user` VARCHAR(100) NOT NULL COMMENT 'SSH 用户名',
    `ssh_auth_type` VARCHAR(20) NOT NULL COMMENT 'SSH 认证方式: password/private_key',
    `ssh_password_encrypted` TEXT COMMENT 'SSH 密码密文',
    `ssh_private_key_encrypted` TEXT COMMENT 'SSH 私钥密文',
    `ssh_private_key_passphrase_encrypted` TEXT COMMENT 'SSH 私钥口令密文',
    `agent_id` VARCHAR(64) DEFAULT NULL COMMENT 'Agent ID',
    `agent_token_hash` VARCHAR(255) DEFAULT NULL COMMENT 'Agent Token 哈希',
    `agent_status` VARCHAR(20) NOT NULL DEFAULT 'offline' COMMENT 'Agent 状态: online/offline',
    `last_heartbeat_at` DATETIME DEFAULT NULL COMMENT '最后心跳时间',
    `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记: 0未删除,1已删除',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    `delete_token` VARCHAR(64) NOT NULL DEFAULT 'ACTIVE' COMMENT '软删除唯一标识',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_servers_host_delete_token` (`host`, `delete_token`),
    UNIQUE KEY `uk_servers_agent_id` (`agent_id`),
    KEY `idx_servers_deleted` (`deleted`),
    KEY `idx_servers_status` (`status`),
    KEY `idx_servers_agent_status` (`agent_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务器表';
