logging:
  level:
    com.susumonitor.server: DEBUG
    com.susumonitor.server.module.auth.mapper: INFO
    org.springframework.security: INFO
    org.mybatis: INFO

spring:
  flyway:
    enabled: true

susumonitor:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
